server:
  port: 9095

spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.200.145.199:5432/scm
    characterEncoding: UTF-8
    username: admin
    password: 1234
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: hyejahong218@gmail.com
    password: ropicekornccnyjp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp

mybatis:
  config-location: classpath:config/myBatis.xml



